### ISSUE TITLE
Drush commands not working

### ISSUE THREAD

**Issue by gokhanozgur** [amazeeio/drupal-integrations#6]
Hi,

When I run `lando drush` in command line I was seen error like down section below.  Also, in addition lagoon commands not working. If I delete drush folder in my root project folder drush command works but I lose lagoon commands.

I was try something:

- composer require consolidation/site-alias -> same result
- https://gitlab.urz.uni-heidelberg.de/EbertMichael/lagoonize_template_files/-/blob/deda5d250f8436cdd12505e16d47fb1595ffc40d/drush/aliases.drushrc.php -> diff error result
- 

Here this error view:

`PHP Fatal error:  Uncaught Error: Interface 'Drush\SiteAlias\SiteAliasManagerAwareInterface' not found in /app/drush/Commands/contrib/drupal_integrations/src/LagoonCommands.php:16
Stack trace:
#0 /opt/drush8/vendor/drush/drush/includes/annotationcommand_adapter.inc(321): include_once()
#1 /opt/drush8/vendor/drush/drush/includes/annotationcommand_adapter.inc(297): annotationcommand_adapter_create_commandfile_instance('/app/drush/Comm...', '\\Drush\\Commands...')
#2 /opt/drush8/vendor/drush/drush/includes/annotationcommand_adapter.inc(109): annotationcommand_adapter_get_commands(Array)
#3 /opt/drush8/vendor/drush/drush/includes/command.inc(1128): annotationcommand_adapter_commands()
#4 /opt/drush8/vendor/drush/drush/includes/command.inc(1426): drush_get_commands()
#5 /opt/drush8/vendor/drush/drush/includes/preflight.inc(591): drush_parse_command()
#6 /opt/drush8/vendor/drush/drush/includes/preflight.inc(65): drush_preflight_command_dispatch()
#7 /opt/drush8/vendor/drush/drush/drush.php(12): drush_main()
#8 {main}
  thrown in /app/drush/Commands/contrib/drupal_integrations/src/LagoonCommands.php on line 16
Drush command terminated abnormally due to an unrecoverable error.                                                                                                                                                                                       [error]
Error: Uncaught Error: Interface 'Drush\SiteAlias\SiteAliasManagerAwareInterface' not found in /app/drush/Commands/contrib/drupal_integrations/src/LagoonCommands.php:16
Stack trace:
#0 /opt/drush8/vendor/drush/drush/includes/annotationcommand_adapter.inc(321): include_once()
#1 /opt/drush8/vendor/drush/drush/includes/annotationcommand_adapter.inc(297): annotationcommand_adapter_create_commandfile_instance('/app/drush/Comm...', '\\Drush\\Commands...')
#2 /opt/drush8/vendor/drush/drush/includes/annotationcommand_adapter.inc(109): annotationcommand_adapter_get_commands(Array)
#3 /opt/drush8/vendor/drush/drush/includes/command.inc(1128): annotationcommand_adapter_commands()
#4 /opt/drush8/vendor/drush/drush/includes/command.inc(1426): drush_get_commands()
#5 /opt/drush8/vendor/drush/drush/includes/preflight.inc(591): drush_parse_command()
#6 /opt/drush8/vendor/drush/drush/includes/preflight.inc(65): drush_preflight_command_dispatch()
#7 /opt/drush8/vendor/drush/drush/drush.php(12): drush_main()
#8 {main}
  thrown in /app/drush/Commands/contrib/drupal_integrations/src/LagoonCommands.php, line 16`

**Comment by tobybellwood** [comment]
ok, there's a few things at play here:

this repo (drupal-integrations) is designed for use with Drush 9 and above - and instead of using the alias stub to request aliases from Lagoon, it uses the wildcard system within Drush to generate them (therefore doesn't use the drush-alias service)

In order for this to work, drush needs to know how to talk to the Lagoon API and SSH services - so they need to be set properly in the .lagoon.yml file (wo do this for a test cluster at https://github.com/amazeeio/drupal-example-simple/blob/test6/.lagoon.yml#L5-L6). If you're not using the amazee.io-hosted Lagoon(s), this step is essential for these services to work - and compatibility isn't guaranteed with Lagoon versions <2.x (currently [2.3.0](https://github.com/uselagoon/lagoon/releases/tag/v2.3.0)

Also noting that the scaffold template linked in the issue is veeeery old - our most current ones are in https://github.com/uselagoon - e.g. drupal9-base - and they do work out of the box with Lando

**Comment by bomoko** [comment]
Closing this due to inactivity. Please feel free to open it again if required.
